# Numpy tutorials


It is a genral purpose array processing package

# Array
It is a data structure that stores value of same data type. The difference between list is that list can store values of different data types whereas arrays can store one data type values.

In [1]:
# to install any libraries
# pip install numpy

In [1]:
import numpy as np

In [3]:
my_lst=[1,2,3,4,5]
type(my_lst)

list

In [4]:
arr=np.array(my_lst) # used to convert a list to array
type(arr)

numpy.ndarray

In [3]:
test1=[1,2,3,"benz"]
test=np.array(test1)
test

array(['1', '2', '3', 'benz'], dtype='<U11')

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
arr.shape

(5,)

In [7]:
#multinested array
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
list3=[11,12,13,14,15]
arr1=np.array([list1,list2,list3])

In [8]:
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [9]:
arr1.shape

(3, 5)

In [10]:
arr1.reshape(5,3)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

The two square brackets in the opening and closing of the array indicates that the dimension of the matrix. If 2 square brackets then it is 2 dimension and so on

# Indexing


In [11]:
arr

array([1, 2, 3, 4, 5])

In [12]:
arr[3]

4

In [13]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [14]:
arr1[:,:] # the left side of the coma indicates the rows of the matrix and the right side (columns)
        # If we put colon : , then it indicates everything arr1[:,:]
    

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [15]:
arr1[1:,2:]

array([[ 8,  9, 10],
       [13, 14, 15]])

In [16]:
arr1[:,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15]])

In [19]:
arr1[1:3,2:4]

array([[ 8,  9],
       [13, 14]])

In [21]:
arr2=np.arange(0,10)

In [22]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
# theres another thing in arange that is called as step. It'll be used to to specify 
# the amount of number that is missed between 2 values
arr3=np.arange(0,10,2) # np.arange(start value, end value, step value)
arr3


array([0, 2, 4, 6, 8])

In [27]:
np.linspace(0,10,50) # gives 50 equally distributed points between the two given values

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [28]:
arr

array([1, 2, 3, 4, 5])

In [29]:
## copy function and broadcasting
arr

array([1, 2, 3, 4, 5])

In [30]:
arr[1:]=100
arr


array([  1, 100, 100, 100, 100])

In [31]:
arr4=arr
arr4[1:]=500
arr4



array([  1, 500, 500, 500, 500])

In [32]:
arr # when printing this, it gets updated using the reference value that we used (* arr4= arr)

array([  1, 500, 500, 500, 500])

In [33]:
# inorder to avoid ths copy() is used
arr=np.arange(0,6)

In [34]:
arr


array([0, 1, 2, 3, 4, 5])

In [35]:
arr1=arr.copy()
arr1

array([0, 1, 2, 3, 4, 5])

In [36]:
arr1[2:]=100
arr1

array([  0,   1, 100, 100, 100, 100])

In [37]:
arr

array([0, 1, 2, 3, 4, 5])

This above set of codes show us the usage of copy() function

In [41]:
random= np.random.rand(4,4)

In [42]:
print(random)

[[0.14511927 0.72136677 0.23206941 0.7250521 ]
 [0.19091754 0.40705727 0.68275301 0.75089465]
 [0.74209369 0.91318842 0.36088134 0.70973602]
 [0.83767838 0.72026009 0.53894159 0.55477513]]


In [46]:

mup=np.ones(3,dtype=int)
print(mup)

[1 1 1]


In [47]:
mup/2

array([0.5, 0.5, 0.5])

In [48]:
mup=np.arange(0,10)

In [49]:
mup

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
mup<5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [51]:
mup[mup<5]

array([0, 1, 2, 3, 4])