# Pandas 


In [1]:
#import pandas
import pandas as pd
import numpy as np

In [2]:
df=pd.DataFrame(np.arange(0,20).reshape(5,4),index=['Row1','Row2','Row3','Row4','Row5'],columns=['Column1','Column2','Column3','Column4'],dtype=int)

In [3]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [4]:
df.to_csv('Test1.csv')# to convert to an excel format sheet

## Accessing the elements 

In [5]:
# .loc
df.loc['Row1']

Column1    0
Column2    1
Column3    2
Column4    3
Name: Row1, dtype: int32

In [6]:
type (df.loc['Row1'])

pandas.core.series.Series

In [32]:
df[['Column1','Column2']]

Column1  Column2
Row1        0        1
Row2        4        5
Row3        8        9
Row4       12       13
Row5       16       17

### Important: 
when we find the type of df.loc, it shows as series
## Data frames:
The data should be having more than one column and one row atleast. If not it is considered as series
## Data series
It can either be a single column or a single row

In [7]:
df.iloc[1:4,1:3]

Column2  Column3
Row2        5        6
Row3        9       10
Row4       13       14

In [8]:
type(df.iloc[1:4,1:3])

pandas.core.frame.DataFrame

In [9]:
df.iloc[:,:1]

Column1
Row1        0
Row2        4
Row3        8
Row4       12
Row5       16

In [10]:
type(df.iloc[:,:1]) # Even though it'll have only one column, this is considered as dataframe. ( look at the output difference between the series type and dataframe type)

pandas.core.frame.DataFrame

In [11]:
df.iloc[:,0]

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: Column1, dtype: int32

In [12]:
type(df.iloc[:,0])

pandas.core.series.Series

## Converting Dataframes into array

In [13]:
df.values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [14]:
df.iloc[1:4,1:3].values

array([[ 5,  6],
       [ 9, 10],
       [13, 14]])

In [15]:
df.iloc[1:4,1:3].values.shape

(3, 2)

# Important function in data science: Null function
## To find the nul values present in each column or row. That is to find the amount of misisng characters or values along the rows or columns

In [16]:
df.isnull()

Column1  Column2  Column3  Column4
Row1    False    False    False    False
Row2    False    False    False    False
Row3    False    False    False    False
Row4    False    False    False    False
Row5    False    False    False    False

In [17]:
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [19]:
df['Column1']

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: Column1, dtype: int32

In [26]:
df['Column1'].value_counts()

12    1
4     1
16    1
8     1
0     1
Name: Column1, dtype: int64

In [31]:
df['Column1'].unique()

array([ 0,  4,  8, 12, 16], dtype=int64)

In [33]:
for col in df.columns:
    print(df[col].value_counts())




12    1
4     1
16    1
8     1
0     1
Name: Column1, dtype: int64
13    1
5     1
17    1
9     1
1     1
Name: Column2, dtype: int64
14    1
6     1
18    1
10    1
2     1
Name: Column3, dtype: int64
7     1
19    1
11    1
3     1
15    1
Name: Column4, dtype: int64
